services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: hoststory-app
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - db
      - mailpit
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - hoststory
  api-go:
    build:
      context: ../host_story_api
      dockerfile: build/docker/Dockerfile
    container_name: hoststory-api
    ports:
      - "8081:8082"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=hoststory_dev
      - DB_USER=root
      - DB_PASSWORD=root
      - JWT_SECRET=your_very_long_secret_key_123456789
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - db
    networks:
      - hoststory
  vite:
    image: node:20-alpine
    working_dir: /var/www
    volumes:
      - ./:/var/www
    command: sh -c "[ ! -d 'node_modules' ] && npm install; npm run dev"
    ports:
      - "5173:5173"
    networks:
      - hoststory
  nginx:
    image: nginx:alpine
    container_name: hoststory-nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - hoststory
  db:
    image: mysql:8.0
    container_name: hoststory-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hoststory_dev
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - hoststory
  mailpit:
    image: axllent/mailpit:latest
    container_name: hoststory-mailpit
    ports:
      - "8026:8025"
      - "1025:1025"
    networks:
      - hoststory
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: hoststory-phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - hoststory
volumes:
  mysql-data:
networks:
  hoststory:
    driver: bridge
